export enum Commands {
  NEXT = 'NEXT',
  PREVIOUS = 'PREVIOUS',
  CHAIN_CONTEXT_CHANGED = 'CHAIN_CONTEXT_CHANGED',
  SELECT_BUDGET = 'SELECT_BUDGET',
  BUY_NATIVE = 'BUY_NATIVE',
  BUY_GLM = 'BUY_GLM',
  RESTART = 'RESTART',
  CHOOSE_NETWORK = 'CHOOSE_NETWORK',
}
